FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["src/Services/Authorization/Authorization.API/Authorization.API.csproj", "src/Services/Authorization/Authorization.API/"]
RUN dotnet restore "src/Services/Authorization/Authorization.API/Authorization.API.csproj"
COPY . .
WORKDIR "/src/src/Services/Authorization/Authorization.API"
RUN dotnet build "Authorization.API.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Authorization.API.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Authorization.API.dll"]
